### ISSUE TITLE
tech.ml.datatype mentioned in the doc

### ISSUE THREAD

**Issue by daslu** [scicloj/tablecloth#102]
https://github.com/scicloj/tablecloth/blob/1e9c8d88c46cdf4492f8fd0e219b4f6af94886a9/docs/index.Rmd#L138

`tech.datatype` is not active anymore. 

It'd make more sense to mention either `tech.ml.dataset` or `dtype-next` here.

**Comment by genmeblog** [comment]
Thanks Daniel. Can you make a PR or update directly? I will refresh docs and publish then.

**Comment by adham-omran** [comment]
The Columns section makes a similar mention, should this mention be removed?

https://github.com/scicloj/tablecloth/blob/ee091ed8afab3a3d52371c2234a4aa65e21214ec/docs/index.Rmd#L875

Becomes _Column is a special `tech.ml.dataset` structure. For our purposes we cat treat columns as typed and named sequence bound to particular dataset._

I can make a PR for this.

**Comment by genmeblog** [comment]
Thanks for spotting it. Yes, please, PR welcome!
