### ISSUE TITLE
Feature request: view each column's datatype below the column name

### ISSUE THREAD

**Issue by ashimapanjwani** [scicloj/tablecloth#12]
It can be something similar to tibbles in R

![iris-dataset](https://user-images.githubusercontent.com/33724707/104916647-5e8bb200-59b8-11eb-839c-3e321bb7ecd9.png)

**Comment by genmeblog** [comment]
Thanks! Good idea, but whole printing is done in TMD (here: https://github.com/techascent/tech.ml.dataset/blob/master/src/tech/v3/dataset/print.clj#L93) so I think it should belong there.
It shouldn't be hard for Chris to make it as I look at the code.

**Comment by ashimapanjwani** [comment]
@genmeblog This issue can be closed since a corresponding issue has been opened in TMD (https://github.com/techascent/tech.ml.dataset/issues/196)
