### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by ashimapanjwani** [scicloj/tablecloth#14]
- Input stream documentation is missing under [Dataset creation](https://scicloj.github.io/tablecloth/index.html#Dataset_creation); 
- Under [Introduction](https://scicloj.github.io/tablecloth/index.html#Introduction), where the links to the documentation of `tech.ml.dataset` and `tech.ml.datatype` have been provided
  - Maybe change Date/time library to dtype-next (since tech.datatype has been superceded by dtype-next); 
  - Change the Dataset link since it is broken

**Comment by genmeblog** [comment]
Ok. Are you able to provide PR for that?

**Comment by daslu** [comment]
Related discussion about he intput stream support:
https://clojurians.zulipchat.com/#narrow/stream/236259-tech.2Eml.2Edataset.2Edev/topic/input.20stream.20dataset.20generation
