### ISSUE TITLE
(repeatedly rand) is running indefinitely despite other columns being finite in a dataset

### ISSUE THREAD

**Issue by ashimapanjwani** [scicloj/tablecloth#15]
Eg:
```Clojure
(tablecloth/dataset {:x (range 1 (inc 10))
                     :y (repeatedly rand)})
```

**Comment by genmeblog** [comment]
It's not fixable unfortunatelly during dataset creation. The main obstacle is that we don't know upfront what is the number of rows at this stage.

You can add infinite column to existing dataset though (because the number of rows is known)

**Comment by genmeblog** [comment]
I'm closing this. To overcome this you can:

a) add column to already existed dataset
b) use `let-dataset`
