### ISSUE TITLE
add-or-replace-column(s) -> add-column(s)

### ISSUE THREAD

**Issue by genmeblog** [scicloj/tablecloth#16]
as @skallinen suggested let's rename `add-or-replace-column(s)` -> `add-column(s)`. Leaving the former as deprecated.

**Comment by ashimapanjwani** [comment]
@genmeblog Can I pick this up?

**Comment by genmeblog** [comment]
Yes!

**Comment by skallinen** [comment]
ah great. thank you and sorry noticed this issue only now
