### ISSUE TITLE
Docs Typo

### ISSUE THREAD

**Issue by wongjoel** [scicloj/tablecloth#2]
There's a typo in the docs for selecting rows. It says:

> Select fourth row
>
>``` clojure
>(api/select-rows DS 4)
>```

But the code actually selects the fifth row, since the selection is zero indexed. (I noticed because I just got caught out on if the selection is zero-indexed or one-indexed)

I would submit a PR, but not sure which file is the source for the docs.

Thanks for all the work, I've been enjoying reading through the docs and seeing the design of this api (I hadn't seen Dplyr before this)

**Comment by genmeblog** [comment]
Thanks for catching this. The code for docs is in the RMarkdown (https://github.com/scicloj/tablecloth/blob/master/docs/index.Rmd#L1294) file. I render documentation in R calling `rmarkdown::render("docs/index.Rmd","all")`

Don't bother with it, I'll fix it soon.

**Comment by genmeblog** [comment]
fixed in pre-alpha9 (will be deployed soon).
