### ISSUE TITLE
reorder-columns on empty dataset returns nil

### ISSUE THREAD

**Issue by behrica** [scicloj/tablecloth#36]
It feels wrong. An empty dataset is "a dataset", so no operation on it should return `nil`,
I believe.

```clojure
(tc/reorder-columns (tc/dataset {}) [:what-ever])
-> nil
```

**Comment by genmeblog** [comment]
`reorder-columns` relies on `tech.v3.dataset/select-columns`. Seems that TMD returns `nil` in this case. I need to check it and when it's true I'll fill an issue in TMD.

**Comment by genmeblog** [comment]
Confirmed:

```clojure
(ds/select-columns (ds/->dataset {}) [])
;; => nil
```

**Comment by genmeblog** [comment]
btw. if you want an empty dataset with TC just call `(tc/dataset)`
