### ISSUE TITLE
tablecloth.api ns is not very Cursive-friendly

### ISSUE THREAD

**Issue by simongray** [scicloj/tablecloth#58]
Seems like a really interesting library, but...

The primary namespace makes use of `tech.v3.datatype.export-symbols/export-symbols` to expose functions in the `tablecloth.api` namespace. This is also the only namespace referenced in the usage example in the README.

Nearly single symbol in this namespace cannot be resolved using static analysis, resulting in improper syntax highlighting, no docstrings and no arglists displayed in my editor's UI. This applies to Cursive (which is one of the most popular Clojure editors), but I'm sure it basically also applies in some way to every single editor which _doesn't_ resolve symbols dynamically (like is done with cider).

May I suggest a slightly less "magic" way of defining these symbols...? This would create a much better experience for everyone not using emacs.

**Comment by genmeblog** [comment]
Thanks! There is a solution for that but need to be implemented. More discussion here: https://clojurians.zulipchat.com/#narrow/stream/151924-data-science/topic/tech.2Eml.2Edataset/near/264019964

**Comment by simongray** [comment]
Great to hear that.

**Comment by genmeblog** [comment]
it should be fixed now (6.051)
