### ISSUE TITLE
Recent versions of tablecloth conflict with dtype-next

### ISSUE THREAD

**Issue by light-matters** [scicloj/tablecloth#63]
With these dependencies (tablcloth 6.023 and higher),
```clojure
:deps  {org.clojure/clojure       {:mvn/version "RELEASE"}

         cnuernber/dtype-next {:mvn/version "8.023"}
         scicloj/tablecloth {:mvn/version "6.023"}
         }
```
then this buffer,
```clojure
(ns data-analysis.table
  (:require
   [tablecloth.api :as tc]))

(tc/dataset {:col1 5.0
             :col2 10.0})
```
, fails.

In fact, just running the namespace form results in an error:

> 1. Caused by java.io.FileNotFoundException
>    Could not locate com/github/ztellman/primitive_math__init.class,
>    com/github/ztellman/primitive_math.clj or
>    com/github/ztellman/primitive_math.cljc on classpath. Please check that
>    namespaces with dashes use underscores in the Clojure file name.

The library seems to perform fine however in version 6.012.

**Comment by genmeblog** [comment]
I'll bump TC version today. You can try to provide newest version of tech.ml.dataset instead of dtype-next.

**Comment by light-matters** [comment]
The issue seems to have resolved for me now by doing 
```clojure
 cnuernber/dtype-next {:mvn/version "RELEASE"}
 scicloj/tablecloth {:mvn/version "RELEASE"}.
```
So the latest versions must be compatible.

**Comment by genmeblog** [comment]
It's always(!) better to rely on latest version of `tech.ml.dataset`. Dependency is simple: `tablecloth` <- `tech.ml.dataset` <- `dtype-next`. When you change only `dtype-next` version, some thing may break in TMD. TMD and dtype-next are developed in parallel afaik.

**Comment by genmeblog** [comment]
Tablecloth is updated to the newest version (6.076).
