### ISSUE TITLE
Confused by version information

### ISSUE THREAD

**Issue by teodorlu** [scicloj/tablecloth#64]
![image](https://user-images.githubusercontent.com/5285452/159170542-8cf02393-d96a-4816-8c04-e1c50dcffffe.png)

Master is version 6, right? Maybe the README should be updated?

I don't have R tooling installed, so no PR from me this time.

---

_really_ enjoying tablecloth's API - thank you!

**Comment by genmeblog** [comment]
thanks! indeed needs to be updated.
