### ISSUE TITLE
tablecloth/dataset does not throw in case of not existing input file

### ISSUE THREAD

**Issue by behrica** [scicloj/tablecloth#84]
```clojure
(tablecloth.api/dataset "not-existing.csv")
```
does not throw exception, but returns a dataset with some information of error.

Is this on purpose ?

```clojure
(tech.v3.dataset/->dataset "not-existing.csv")
```

throws file-not-found exception , as I would have expected.

**Comment by genmeblog** [comment]
TC allows to create a singleton dataset (one row and column) just from the value. It was done only when other `->dataset` cases failed.
It has been discussed somewhere in the past already (on Zulip, probably with jsa). After this, some options were introduced: https://github.com/scicloj/tablecloth/blob/master/src/tablecloth/api/dataset.clj#L60

I see this can be a little bit unfortunate, maybe `stack-trace?` option should be `true` by default?

**Comment by behrica** [comment]
I find it scary,  that it does not throw an exception,  if file not found. So maybe we can handle FileNotFoundException differently

**Comment by genmeblog** [comment]
Good idea.
